test_that("make_deg_display", {
  expect_equal(make_deg_display(1, 1), "1st_pc")
  expect_equal(make_deg_display(1, 0.5), "1st_sib")
  expect_equal(make_deg_display(2), "2nd")
  expect_equal(make_deg_display(3), "3rd")
  expect_equal(make_deg_display(4), "4th")
  expect_equal(make_deg_display(10), "10th")
  expect_equal(make_deg_display(11), "11th")
  expect_equal(make_deg_display(12), "12th")
  expect_equal(make_deg_display(13), "13th")
  expect_equal(make_deg_display(21), "21st")
  expect_equal(make_deg_display(22), "22nd")
  expect_equal(make_deg_display(23), "23rd")
})
