test_that("matchY pattern 1", {
  qHap <- c("10", "15, 16", "20")
  rHap <- c("10", "15, 16", "20")
  judgeMat <- matchY(qHap, rHap)
  expect_equal(nrow(judgeMat), 3)
  expect_equal(ncol(judgeMat), 4)
  expect_equal(judgeMat[1, 1], 0)
  expect_equal(judgeMat[1, 2], 0)
  expect_equal(judgeMat[1, 3], 0)
  expect_equal(judgeMat[1, 4], 0)
  expect_equal(judgeMat[2, 1], 0)
  expect_equal(judgeMat[2, 2], 0)
  expect_equal(judgeMat[2, 3], 0)
  expect_equal(judgeMat[2, 4], 0)
  expect_equal(judgeMat[3, 1], 0)
  expect_equal(judgeMat[3, 2], 0)
  expect_equal(judgeMat[3, 3], 0)
  expect_equal(judgeMat[3, 4], 0)
})

test_that("matchY pattern 2", {
  qHap <- c("10", "15, 16", "")
  rHap <- c("10", "15, 17", "22")
  judgeMat <- matchY(qHap, rHap)
  expect_equal(nrow(judgeMat), 3)
  expect_equal(ncol(judgeMat), 4)
  expect_equal(judgeMat[1, 1], 0)
  expect_equal(judgeMat[1, 2], 1)
  expect_equal(judgeMat[1, 3], 0)
  expect_equal(judgeMat[1, 4], 1)
  expect_equal(judgeMat[2, 1], 0)
  expect_equal(judgeMat[2, 2], 0)
  expect_equal(judgeMat[2, 3], 1)
  expect_equal(judgeMat[2, 4], 1)
  expect_equal(judgeMat[3, 1], 0)
  expect_equal(judgeMat[3, 2], 1)
  expect_equal(judgeMat[3, 3], 0)
  expect_equal(judgeMat[3, 4], 1)
})

test_that("matchY pattern 3", {
  qHap <- c("10", "15", "20")
  rHap <- c("10", "15, 17", "22")
  judgeMat <- matchY(qHap, rHap)
  expect_equal(nrow(judgeMat), 3)
  expect_equal(ncol(judgeMat), 4)
  expect_equal(judgeMat[1, 1], 0)
  expect_equal(judgeMat[1, 2], 0)
  expect_equal(judgeMat[1, 3], 1)
  expect_equal(judgeMat[1, 4], 1)
  expect_equal(judgeMat[2, 1], 0)
  expect_equal(judgeMat[2, 2], 1)
  expect_equal(judgeMat[2, 3], 0)
  expect_equal(judgeMat[2, 4], 1)
  expect_equal(judgeMat[3, 1], 0)
  expect_equal(judgeMat[3, 2], 0)
  expect_equal(judgeMat[3, 3], 2)
  expect_equal(judgeMat[3, 4], 2)
})
