// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matchY2
IntegerMatrix matchY2(CharacterVector qHap, CharacterVector rHap);
RcppExport SEXP _relsearch_matchY2(SEXP qHapSEXP, SEXP rHapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type qHap(qHapSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type rHap(rHapSEXP);
    rcpp_result_gen = Rcpp::wrap(matchY2(qHap, rHap));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_relsearch_matchY2", (DL_FUNC) &_relsearch_matchY2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_relsearch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
