# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

searchPos <- function(vec, target) {
    .Call(`_relsearch_searchPos`, vec, target)
}

#' @export
kinLike2 <- function(qgt, rgt, af, afAl, probIBD, consMu, myu, ape) {
    .Call(`_relsearch_kinLike2`, qgt, rgt, af, afAl, probIBD, consMu, myu, ape)
}

#' @export
matchY2 <- function(qHap, rHap) {
    .Call(`_relsearch_matchY2`, qHap, rHap)
}

